import fs from 'node:fs';
import { PDFParse } from 'pdf-parse';
const { parseFncBulletin } = await import('./server/services/fncPrice.js');
const buf = fs.readFileSync(process.argv[2]);
const p = new PDFParse({ data: new Uint8Array(buf) });
const { text } = await p.getText();
await p.destroy();
fs.writeFileSync('./_fixture.txt', text);
const d = parseFncBulletin(text, 'http://x');
console.log('fecha:', d.priceDate, '| carga:', d.cargaCop, '| FR base:', d.baseYieldFactor);
console.log('NY:', d.nyCloseUscentLb, '| pasilla:', d.pasillaCopKg);
console.log('excelso COP/kg (FR94):', d.excelsoCopKg);
console.log('filas factor:', d.yieldTable.length, d.yieldTable[0], d.yieldTable.at(-1));
console.log('sucursales:', d.branches.length, d.branches.slice(0,3));
