import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto('http://localhost:4321/', { waitUntil: 'load', timeout: 20000 });
await page.waitForTimeout(800);
const stay = page.locator('text=Stay in Spanish');
if (await stay.count()) await stay.click();
await page.evaluate(() => window.scrollTo(0, document.body.scrollHeight));
await page.waitForTimeout(300);
await page.screenshot({ path: '/tmp/claude-1000/-home-mike-dev-work-github-com-dobleyo/ae6ed510-dca4-46d0-80d8-d24097e041fb/scratchpad/footer-light.png' });
await browser.close();
console.log('done');
