name: 🚀 Deploy to cPanel (incremental)

on:
  push:
    branches:
      - main   # o master si tu rama principal es esa

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Deploy con FTP (solo archivos cambiados)
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/
          protocol: ftp
          # ⚡ Esto asegura que solo se suban archivos nuevos o modificados
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/.env

